# TensorFlow Basics

In [32]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.11.0


In [33]:
hello = tf.constant("Hello ")
world = tf.constant("World")
type(hello)
hello

<tf.Tensor 'Const_10:0' shape=() dtype=string>

To actually print we have to go with session in tensorflow or else it will give output it as it is tensor

In [7]:
with tf.Session() as sess:
    result = sess.run(hello+world)
       

b'Hello World'


In [8]:
result

b'Hello World'

In [9]:
a = tf.constant(10)
b = tf.constant(20)

with tf.Session() as ses:
    result = ses.run(a+b)
result

30

In [21]:
const = tf.constant(10)
fill_mat = tf.fill((4,4),10) 

In [22]:
myzeros = tf.zeros((4,4))


In [23]:
myones = tf.ones((4,4))


In [24]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [25]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [26]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [30]:
with tf.Session() as sess:
    for op in my_ops:
        print(sess.run(op))
        print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.6332109  -1.3551184  -0.9108659  -1.9567713 ]
 [-0.79172194  0.74659044  0.7021712   0.62064373]
 [ 1.2558634   0.2865663  -0.9137801  -0.7786702 ]
 [-0.01411945 -0.67570156 -1.348905   -0.81643456]]


[[0.475415   0.05836058 0.41324508 0.8727281 ]
 [0.2840997  0.44610322 0.9585949  0.20458281]
 [0.38635767 0.73156166 0.36287618 0.95682573]
 [0.34365463 0.19732189 0.5330198  0.73464954]]




#Manually creating matrix

In [36]:
a = tf.constant([ [1,2],
                  [3,4] ])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [38]:
with tf.Session() as sess:
    print(sess.run(a))

[[1 2]
 [3 4]]


Matrix Multiplication

In [52]:
b = tf.constant([ [4], [5] ])
b.get_shape()


TensorShape([Dimension(2), Dimension(1)])

In [51]:
with tf.Session() as sess:
    result = tf.matmul(a,b)
    print(sess.run(result))

[[14]
 [32]]
